//
// CreateAccountRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAccountRequest: Codable, JSONEncodable, Hashable {

    public var environment: String
    public var index: Int
    public var mint: String
    public var tx: Data

    public init(environment: String, index: Int, mint: String, tx: Data) {
        self.environment = environment
        self.index = index
        self.mint = mint
        self.tx = tx
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case environment
        case index
        case mint
        case tx
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(environment, forKey: .environment)
        try container.encode(index, forKey: .index)
        try container.encode(mint, forKey: .mint)
        try container.encode(tx, forKey: .tx)
    }
}

