//
// AccountInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccountInfo: Codable, JSONEncodable, Hashable {

    public var account: String
    public var isMint: Bool
    public var isOwner: Bool
    public var isTokenAccount: Bool
    public var owner: String?
    public var program: String?
    public var tokens: [TokenInfo]?

    public init(account: String, isMint: Bool, isOwner: Bool, isTokenAccount: Bool, owner: String? = nil, program: String? = nil, tokens: [TokenInfo]? = nil) {
        self.account = account
        self.isMint = isMint
        self.isOwner = isOwner
        self.isTokenAccount = isTokenAccount
        self.owner = owner
        self.program = program
        self.tokens = tokens
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case isMint
        case isOwner
        case isTokenAccount
        case owner
        case program
        case tokens
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(account, forKey: .account)
        try container.encode(isMint, forKey: .isMint)
        try container.encode(isOwner, forKey: .isOwner)
        try container.encode(isTokenAccount, forKey: .isTokenAccount)
        try container.encodeIfPresent(owner, forKey: .owner)
        try container.encodeIfPresent(program, forKey: .program)
        try container.encodeIfPresent(tokens, forKey: .tokens)
    }
}

