//
// BalanceResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BalanceResponse: Codable, JSONEncodable, Hashable {

    public var balance: String
    public var mints: AnyCodable
    public var tokens: [BalanceToken]

    public init(balance: String, mints: AnyCodable, tokens: [BalanceToken]) {
        self.balance = balance
        self.mints = mints
        self.tokens = tokens
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case balance
        case mints
        case tokens
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(balance, forKey: .balance)
        try container.encode(mints, forKey: .mints)
        try container.encode(tokens, forKey: .tokens)
    }
}

