//
// CloseAccountRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CloseAccountRequest: Codable, JSONEncodable, Hashable {

    public var commitment: Commitment
    public var account: String
    public var environment: String
    public var index: Int
    public var mint: String
    public var reference: String?
    @available(*, deprecated, message: "This property is deprecated.")
    public var referenceId: String?
    @available(*, deprecated, message: "This property is deprecated.")
    public var referenceType: String?

    public init(commitment: Commitment, account: String, environment: String, index: Int, mint: String, reference: String? = nil, referenceId: String? = nil, referenceType: String? = nil) {
        self.commitment = commitment
        self.account = account
        self.environment = environment
        self.index = index
        self.mint = mint
        self.reference = reference
        self.referenceId = referenceId
        self.referenceType = referenceType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case commitment
        case account
        case environment
        case index
        case mint
        case reference
        case referenceId
        case referenceType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(commitment, forKey: .commitment)
        try container.encode(account, forKey: .account)
        try container.encode(environment, forKey: .environment)
        try container.encode(index, forKey: .index)
        try container.encode(mint, forKey: .mint)
        try container.encodeIfPresent(reference, forKey: .reference)
        try container.encodeIfPresent(referenceId, forKey: .referenceId)
        try container.encodeIfPresent(referenceType, forKey: .referenceType)
    }
}

