//
// ClusterType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ClusterType: String, Codable, CaseIterable {
    case custom = "Custom"
    case solanaDevnet = "SolanaDevnet"
    case solanaMainnet = "SolanaMainnet"
    case solanaTestnet = "SolanaTestnet"
}
