//
// CompiledInnerInstruction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CompiledInnerInstruction: Codable, JSONEncodable, Hashable {

    public var index: Int
    public var instructions: [CompiledInstruction]

    public init(index: Int, instructions: [CompiledInstruction]) {
        self.index = index
        self.instructions = instructions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case index
        case instructions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(index, forKey: .index)
        try container.encode(instructions, forKey: .instructions)
    }
}

