//
// ConfirmedSignatureInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ConfirmedSignatureInfo: Codable, JSONEncodable, Hashable {

    public var signature: String
    public var slot: Int?
    public var err: String?
    public var memo: String?
    public var blockTime: Int?

    public init(signature: String, slot: Int? = nil, err: String? = nil, memo: String? = nil, blockTime: Int? = nil) {
        self.signature = signature
        self.slot = slot
        self.err = err
        self.memo = memo
        self.blockTime = blockTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case signature
        case slot
        case err
        case memo
        case blockTime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(signature, forKey: .signature)
        try container.encodeIfPresent(slot, forKey: .slot)
        try container.encodeIfPresent(err, forKey: .err)
        try container.encodeIfPresent(memo, forKey: .memo)
        try container.encodeIfPresent(blockTime, forKey: .blockTime)
    }
}

