//
// ConfirmationStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ConfirmationStatus: String, Codable, CaseIterable {
    case processed = "processed"
    case confirmed = "confirmed"
    case finalized = "finalized"
}
