//
// Context.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Context: Codable, JSONEncodable, Hashable {

    public var slot: Int?

    public init(slot: Int? = nil) {
        self.slot = slot
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slot
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(slot, forKey: .slot)
    }
}

