//
// CreateAccountRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAccountRequest: Codable, JSONEncodable, Hashable {

    public var commitment: Commitment
    public var environment: String
    public var index: Int
    public var lastValidBlockHeight: Int
    public var mint: String
    public var reference: String?
    @available(*, deprecated, message: "This property is deprecated.")
    public var referenceId: String?
    @available(*, deprecated, message: "This property is deprecated.")
    public var referenceType: String?
    public var tx: String

    public init(commitment: Commitment, environment: String, index: Int, lastValidBlockHeight: Int, mint: String, reference: String? = nil, referenceId: String? = nil, referenceType: String? = nil, tx: String) {
        self.commitment = commitment
        self.environment = environment
        self.index = index
        self.lastValidBlockHeight = lastValidBlockHeight
        self.mint = mint
        self.reference = reference
        self.referenceId = referenceId
        self.referenceType = referenceType
        self.tx = tx
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case commitment
        case environment
        case index
        case lastValidBlockHeight
        case mint
        case reference
        case referenceId
        case referenceType
        case tx
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(commitment, forKey: .commitment)
        try container.encode(environment, forKey: .environment)
        try container.encode(index, forKey: .index)
        try container.encode(lastValidBlockHeight, forKey: .lastValidBlockHeight)
        try container.encode(mint, forKey: .mint)
        try container.encodeIfPresent(reference, forKey: .reference)
        try container.encodeIfPresent(referenceId, forKey: .referenceId)
        try container.encodeIfPresent(referenceType, forKey: .referenceType)
        try container.encode(tx, forKey: .tx)
    }
}

