//
// GetTransactionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetTransactionResponse: Codable, JSONEncodable, Hashable {

    public var signature: String
    public var status: RpcResponseAndContext
    public var transaction: TransactionResponse

    public init(signature: String, status: RpcResponseAndContext, transaction: TransactionResponse) {
        self.signature = signature
        self.status = status
        self.transaction = transaction
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case signature
        case status
        case transaction
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(signature, forKey: .signature)
        try container.encode(status, forKey: .status)
        try container.encode(transaction, forKey: .transaction)
    }
}

