//
// RequestAirdropRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RequestAirdropRequest: Codable, JSONEncodable, Hashable {

    public var account: String
    public var amount: String?
    public var commitment: Commitment
    public var environment: String
    public var index: Int
    public var mint: String

    public init(account: String, amount: String? = nil, commitment: Commitment, environment: String, index: Int, mint: String) {
        self.account = account
        self.amount = amount
        self.commitment = commitment
        self.environment = environment
        self.index = index
        self.mint = mint
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case amount
        case commitment
        case environment
        case index
        case mint
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(account, forKey: .account)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encode(commitment, forKey: .commitment)
        try container.encode(environment, forKey: .environment)
        try container.encode(index, forKey: .index)
        try container.encode(mint, forKey: .mint)
    }
}

