//
// RpcResponseAndContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RpcResponseAndContext: Codable, JSONEncodable, Hashable {

    public var context: Context
    public var value: SignatureStatus

    public init(context: Context, value: SignatureStatus) {
        self.context = context
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case context
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(context, forKey: .context)
        try container.encode(value, forKey: .value)
    }
}

