//
// SignatureStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignatureStatus: Codable, JSONEncodable, Hashable {

    public enum ConfirmationStatus: String, Codable, CaseIterable {
        case processed = "processed"
        case confirmed = "confirmed"
        case finalized = "finalized"
    }
    public var slot: Double?
    public var confirmations: Double?
    public var err: AnyCodable?
    public var confirmationStatus: ConfirmationStatus?

    public init(slot: Double? = nil, confirmations: Double? = nil, err: AnyCodable? = nil, confirmationStatus: ConfirmationStatus? = nil) {
        self.slot = slot
        self.confirmations = confirmations
        self.err = err
        self.confirmationStatus = confirmationStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slot
        case confirmations
        case err
        case confirmationStatus
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(slot, forKey: .slot)
        try container.encodeIfPresent(confirmations, forKey: .confirmations)
        try container.encodeIfPresent(err, forKey: .err)
        try container.encodeIfPresent(confirmationStatus, forKey: .confirmationStatus)
    }
}

