//
// TokenAmount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TokenAmount: Codable, JSONEncodable, Hashable {

    public var amount: String
    public var decimals: Int
    public var uiAmount: Int?
    public var uiAmountString: String?

    public init(amount: String, decimals: Int, uiAmount: Int? = nil, uiAmountString: String? = nil) {
        self.amount = amount
        self.decimals = decimals
        self.uiAmount = uiAmount
        self.uiAmountString = uiAmountString
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case decimals
        case uiAmount
        case uiAmountString
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(decimals, forKey: .decimals)
        try container.encodeIfPresent(uiAmount, forKey: .uiAmount)
        try container.encodeIfPresent(uiAmountString, forKey: .uiAmountString)
    }
}

