//
// TokenInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TokenInfo: Codable, JSONEncodable, Hashable {

    public var account: String
    public var balance: String?
    public var closeAuthority: String?
    public var decimals: Int
    public var mint: String
    public var owner: String?

    public init(account: String, balance: String? = nil, closeAuthority: String? = nil, decimals: Int, mint: String, owner: String? = nil) {
        self.account = account
        self.balance = balance
        self.closeAuthority = closeAuthority
        self.decimals = decimals
        self.mint = mint
        self.owner = owner
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case balance
        case closeAuthority
        case decimals
        case mint
        case owner
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(account, forKey: .account)
        try container.encodeIfPresent(balance, forKey: .balance)
        try container.encodeIfPresent(closeAuthority, forKey: .closeAuthority)
        try container.encode(decimals, forKey: .decimals)
        try container.encode(mint, forKey: .mint)
        try container.encodeIfPresent(owner, forKey: .owner)
    }
}

