//
// TransactionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionResponse: Codable, JSONEncodable, Hashable {

    public var slot: Double?
    public var transaction: TransactionData
    public var meta: ConfirmedTransactionMeta
    public var blockTime: Double?

    public init(slot: Double? = nil, transaction: TransactionData, meta: ConfirmedTransactionMeta, blockTime: Double? = nil) {
        self.slot = slot
        self.transaction = transaction
        self.meta = meta
        self.blockTime = blockTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slot
        case transaction
        case meta
        case blockTime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(slot, forKey: .slot)
        try container.encode(transaction, forKey: .transaction)
        try container.encode(meta, forKey: .meta)
        try container.encodeIfPresent(blockTime, forKey: .blockTime)
    }
}

