//
// TransactionData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionData: Codable, JSONEncodable, Hashable {

    public var message: AnyCodable
    public var signatures: [String]

    public init(message: AnyCodable, signatures: [String]) {
        self.message = message
        self.signatures = signatures
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case signatures
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(signatures, forKey: .signatures)
    }
}

