//
// TransactionStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TransactionStatus: String, Codable, CaseIterable {
    case committed = "Committed"
    case confirmed = "Confirmed"
    case failed = "Failed"
    case finalized = "Finalized"
    case processing = "Processing"
}
