//
// TransactionErrorType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TransactionErrorType: String, Codable, CaseIterable {
    case badNonce = "BadNonce"
    case invalidAccount = "InvalidAccount"
    case someError = "SomeError"
    case timeout = "Timeout"
    case unknown = "Unknown"
    case webhookFailed = "WebhookFailed"
}
