//
// AirdropStatsDate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AirdropStatsDate: Codable, JSONEncodable, Hashable {

    public var date: String
    public var count: Double

    public init(date: String, count: Double) {
        self.date = date
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(date, forKey: .date)
        try container.encode(count, forKey: .count)
    }
}

