//
// ApiConfigSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiConfigSummary: Codable, JSONEncodable, Hashable {

    public var port: Double
    public var environment: String
    public var solanaRpcEndpoint: String

    public init(port: Double, environment: String, solanaRpcEndpoint: String) {
        self.port = port
        self.environment = environment
        self.solanaRpcEndpoint = solanaRpcEndpoint
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case port
        case environment
        case solanaRpcEndpoint
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(port, forKey: .port)
        try container.encode(environment, forKey: .environment)
        try container.encode(solanaRpcEndpoint, forKey: .solanaRpcEndpoint)
    }
}

