//
// AppConfigMint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppConfigMint: Codable, JSONEncodable, Hashable {

    public var feePayer: String
    public var programId: String
    public var publicKey: String

    public init(feePayer: String, programId: String, publicKey: String) {
        self.feePayer = feePayer
        self.programId = programId
        self.publicKey = publicKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case feePayer
        case programId
        case publicKey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(feePayer, forKey: .feePayer)
        try container.encode(programId, forKey: .programId)
        try container.encode(publicKey, forKey: .publicKey)
    }
}

