//
// AppConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppConfig: Codable, JSONEncodable, Hashable {

    public var app: AppConfigApp
    public var mint: AppConfigMint

    public init(app: AppConfigApp, mint: AppConfigMint) {
        self.app = app
        self.mint = mint
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case app
        case mint
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(app, forKey: .app)
        try container.encode(mint, forKey: .mint)
    }
}

