//
// AppConfigApp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppConfigApp: Codable, JSONEncodable, Hashable {

    public var index: Double
    public var name: String

    public init(index: Double, name: String) {
        self.index = index
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case index
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(index, forKey: .index)
        try container.encode(name, forKey: .name)
    }
}

