//
// AppTransactionError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppTransactionError: Codable, JSONEncodable, Hashable {

    public var id: String
    public var message: String
    public var type: AnyCodable

    public init(id: String, message: String, type: AnyCodable) {
        self.id = id
        self.message = message
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case message
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(message, forKey: .message)
        try container.encode(type, forKey: .type)
    }
}

