//
// BalanceToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BalanceToken: Codable, JSONEncodable, Hashable {

    public var account: String
    public var balance: AnyCodable
    public var mint: String

    public init(account: String, balance: AnyCodable, mint: String) {
        self.account = account
        self.balance = balance
        self.mint = mint
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case balance
        case mint
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(account, forKey: .account)
        try container.encode(balance, forKey: .balance)
        try container.encode(mint, forKey: .mint)
    }
}

