//
// HealthCheckResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HealthCheckResponse: Codable, JSONEncodable, Hashable {

    public var isSolanaOk: Bool
    public var isMogamiOk: Bool
    public var time: String

    public init(isSolanaOk: Bool, isMogamiOk: Bool, time: String) {
        self.isSolanaOk = isSolanaOk
        self.isMogamiOk = isMogamiOk
        self.time = time
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isSolanaOk
        case isMogamiOk
        case time
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isSolanaOk, forKey: .isSolanaOk)
        try container.encode(isMogamiOk, forKey: .isMogamiOk)
        try container.encode(time, forKey: .time)
    }
}

