//
// LatestBlockhashResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LatestBlockhashResponse: Codable, JSONEncodable, Hashable {

    public var blockhash: String

    public init(blockhash: String) {
        self.blockhash = blockhash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blockhash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(blockhash, forKey: .blockhash)
    }
}

