//
// MakeTransferRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MakeTransferRequest: Codable, JSONEncodable, Hashable {

    public var index: Double
    public var tx: AnyCodable

    public init(index: Double, tx: AnyCodable) {
        self.index = index
        self.tx = tx
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case index
        case tx
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(index, forKey: .index)
        try container.encode(tx, forKey: .tx)
    }
}

