//
// MinimumRentExemptionBalanceResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MinimumRentExemptionBalanceResponse: Codable, JSONEncodable, Hashable {

    public var lamports: Double

    public init(lamports: Double) {
        self.lamports = lamports
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lamports
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(lamports, forKey: .lamports)
    }
}

