//
// RequestAirdropRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RequestAirdropRequest: Codable, JSONEncodable, Hashable {

    public var account: String
    public var amount: String?

    public init(account: String, amount: String? = nil) {
        self.account = account
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(account, forKey: .account)
        try container.encodeIfPresent(amount, forKey: .amount)
    }
}

