//
// AppConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppConfig: Codable, JSONEncodable, Hashable {

    public var app: AppConfigApp
    public var environment: AppConfigEnvironment
    public var mint: AppConfigMint
    public var mints: [AppConfigMint]

    public init(app: AppConfigApp, environment: AppConfigEnvironment, mint: AppConfigMint, mints: [AppConfigMint]) {
        self.app = app
        self.environment = environment
        self.mint = mint
        self.mints = mints
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case app
        case environment
        case mint
        case mints
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(app, forKey: .app)
        try container.encode(environment, forKey: .environment)
        try container.encode(mint, forKey: .mint)
        try container.encode(mints, forKey: .mints)
    }
}

